/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RescueModeRouteImport } from './routes/rescue-mode'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PantryIdRouteImport } from './routes/pantry.$id'

const RescueModeRoute = RescueModeRouteImport.update({
  id: '/rescue-mode',
  path: '/rescue-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryIdRoute = PantryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PantryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recipes': typeof RecipesRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/rescue-mode': typeof RescueModeRoute
  '/pantry/$id': typeof PantryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recipes': typeof RecipesRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/rescue-mode': typeof RescueModeRoute
  '/pantry/$id': typeof PantryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRouteWithChildren
  '/receipts': typeof ReceiptsRoute
  '/recipes': typeof RecipesRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/rescue-mode': typeof RescueModeRoute
  '/pantry/$id': typeof PantryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pantry'
    | '/receipts'
    | '/recipes'
    | '/recommendations'
    | '/register'
    | '/rescue-mode'
    | '/pantry/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pantry'
    | '/receipts'
    | '/recipes'
    | '/recommendations'
    | '/register'
    | '/rescue-mode'
    | '/pantry/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/pantry'
    | '/receipts'
    | '/recipes'
    | '/recommendations'
    | '/register'
    | '/rescue-mode'
    | '/pantry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PantryRoute: typeof PantryRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRoute
  RecipesRoute: typeof RecipesRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  RescueModeRoute: typeof RescueModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rescue-mode': {
      id: '/rescue-mode'
      path: '/rescue-mode'
      fullPath: '/rescue-mode'
      preLoaderRoute: typeof RescueModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/$id': {
      id: '/pantry/$id'
      path: '/$id'
      fullPath: '/pantry/$id'
      preLoaderRoute: typeof PantryIdRouteImport
      parentRoute: typeof PantryRoute
    }
  }
}

interface PantryRouteChildren {
  PantryIdRoute: typeof PantryIdRoute
}

const PantryRouteChildren: PantryRouteChildren = {
  PantryIdRoute: PantryIdRoute,
}

const PantryRouteWithChildren =
  PantryRoute._addFileChildren(PantryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PantryRoute: PantryRouteWithChildren,
  ReceiptsRoute: ReceiptsRoute,
  RecipesRoute: RecipesRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  RescueModeRoute: RescueModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
